# Generated by Django 4.2.1 on 2023-06-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_date_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
