# Generated by Django 4.2.1 on 2023-06-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contacting_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
